# https://circleci.com/docs/2.0/configuration-reference/#pre-steps-and-post-steps-requires-version-21
version: 2.1  
jobs:
   build:
     docker:
       - image: circleci/node:latest   # test environment    DockerHub > circleci
     steps:
       - checkout  # checkout the code
       - run: echo "build phase..."
       - run: npm install
       - run: ENV="" npm run build   # environmental variable 'ENV'
   test:
     docker:
       - image: circleci/node:latest
     steps:
       - checkout
       - run: echo "test phase..."
       - run: npm install
       - run: npm run test
 
workflows:
  version: 2
  build-test:  # workflow name   
    jobs:  # each job running in parallel on separate containers except 'requires' case etc
      - test
          # filters:
          #     branches:
          #       only:
          #         - master  # Any branches that match 'only' will run the job.
     
     - build
          # pre-steps: # steps to run before steps defined in the job bar
          #   - run:
          #       command: echo "install custom dependency"
          # post-steps: # steps to run after steps defined in the job bar
          #   - run:
          #       command: echo "upload artifact to s3"
          requires:
            - test   # require 'test' job to be done first 